In [1]:
import pandas as pd 
import numpy as np 
import scipy.stats as sps
import matplotlib.pyplot as plt 
import seaborn as sns 
import sklearn as skl 
from sklearn import preprocessing 
from math import isnan 
import matplotlib

In [19]:
base = pd.read_csv('applications data.csv',index_col = 0)
base_new = base.loc[(base['date'] < 20161101),:]  # only use transactions before 1st Nov.

In [21]:
base_new.tail()

,date,ssn,firstname,lastname,address,zip5,dob,homephone,fraud_label
record,,,,,,,,,
833503,20161031,614489026,EJUJRSUMZ,EEJSTZUT,9034 UERXU RD,4529,20130609,3743139222,0
833504,20161031,20529638,RZRTEJXUT,UXMSSZSX,1452 RJMMA ST,68562,19550212,7155993451,0
833505,20161031,604655517,UTEXRMERT,EZRXRXEZ,8381 RAXMU ST,52826,19470127,9999999999,0
833506,20161031,171974215,EXMUXAZRX,SZUTAURS,9517 XXMMZ ST,58097,19290208,9747929283,0
833507,20161031,985717679,RXMJSAJZE,REAJMAEZ,4205 EZJJU BLVD,9416,19250709,5386413150,0

In [13]:
appli = pd.read_csv('FinalCleanedVariablesNoNa.csv', index_col = 0)

In [15]:
appli.head()

,record,diff_date.ssn,diff_date.fulladdress,diff_date.nameDOB,diff_date.homephone,diff_date.ssn_fulladdress,diff_date.ssn_firstname,diff_date.ssn_lastname,diff_date.ssn_nameDOB,diff_date.ssn_homephone,...,fulladdresshomephone7,fulladdresshomephone14,fulladdresshomephone30,fulladdressnameDOB0,fulladdressnameDOB1,fulladdressnameDOB3,fulladdressnameDOB7,fulladdressnameDOB14,fulladdressnameDOB30,fraud_label
0,1,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,0
1,2,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,1
2,3,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,0
3,4,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,0
4,5,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,0

In [17]:
appli.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000000 entries, 0 to 999999
Columns: 103 entries, record to fraud_label
dtypes: float64(31), int64(72)
memory usage: 793.5 MB

In [24]:
appli_new=appli.copy()

In [25]:
appli_train = appli_new.loc[(appli_new['record'] <= 833507),:]  # only use transactions before 1st Nov.

In [30]:
appli_train.head()

,record,diff_date.ssn,diff_date.fulladdress,diff_date.nameDOB,diff_date.homephone,diff_date.ssn_fulladdress,diff_date.ssn_firstname,diff_date.ssn_lastname,diff_date.ssn_nameDOB,diff_date.ssn_homephone,...,fulladdresshomephone7,fulladdresshomephone14,fulladdresshomephone30,fulladdressnameDOB0,fulladdressnameDOB1,fulladdressnameDOB3,fulladdressnameDOB7,fulladdressnameDOB14,fulladdressnameDOB30,fraud_label
0,1,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,0
1,2,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,1
2,3,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,0
3,4,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,0
4,5,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,365.0,...,1,1,1,1,1,1,1,1,1,0

In [29]:
appli_train = appli_train.reset_index(drop = True)

In [39]:
appli_train['randNum'] = np.random.randint(1, 1000000, appli_train.shape[0])
appli_train['FraudLabel']=appli_train['fraud_label']
# Create a fraud column and random number column for comparison
fraud = appli_train['fraud_label']
appli_train.drop(labels=['fraud_label'], axis=1,inplace = True)
appli_train.insert(0, 'fraud_label', fraud)
appli_train.dtypes

fraud_label                          int64
record                               int64
diff_date.ssn                      float64
diff_date.fulladdress              float64
diff_date.nameDOB                  float64
diff_date.homephone                float64
diff_date.ssn_fulladdress          float64
diff_date.ssn_firstname            float64
diff_date.ssn_lastname             float64
diff_date.ssn_nameDOB              float64
diff_date.ssn_homephone            float64
diff_date.fulladdress_firstname    float64
diff_date.fulladdress_lastname     float64
diff_date.fulladdress_nameDOB      float64
diff_date.fulladdress_homephone    float64
diff_date.firstname_lastname       float64
diff_date.firstname_nameDOB        float64
diff_date.firstname_homephone      float64
diff_date.lastname_nameDOB         float64
diff_date.lastname_homephone       float64
diff_date.nameDOB_homephone        float64
ssn_risk                           float64
fulladdress_risk                   float64
nameDOB_risk                       float64
homephone_risk                     float64
ssn_fulladdress_risk               float64
ssn_nameDOB_risk                   float64
ssn_homephone_risk                 float64
ssn_firstname_risk                 float64
ssn_lastname_risk                  float64
                                    ...
ssnfirstname3                        int64
ssnfirstname7                        int64
ssnfirstname14                       int64
ssnfirstname30                       int64
ssnlastname0                         int64
ssnlastname1                         int64
ssnlastname3                         int64
ssnlastname7                         int64
ssnlastname14                        int64
ssnlastname30                        int64
nameDOBhomephone0                    int64
nameDOBhomephone1                    int64
nameDOBhomephone3                    int64
nameDOBhomephone7                    int64
nameDOBhomephone14                   int64
nameDOBhomephone30                   int64
fulladdresshomephone0                int64
fulladdresshomephone1                int64
fulladdresshomephone3                int64
fulladdresshomephone7                int64
fulladdresshomephone14               int64
fulladdresshomephone30               int64
fulladdressnameDOB0                  int64
fulladdressnameDOB1                  int64
fulladdressnameDOB3                  int64
fulladdressnameDOB7                  int64
fulladdressnameDOB14                 int64
fulladdressnameDOB30                 int64
randNum                              int64
FraudLabel                           int64
Length: 105, dtype: object

## Calculate FDR Table for all the candidate variables

In [41]:
appli_train.isnull().any()
appli_train_2 = appli_train.copy()

In [42]:
Three_Percent = round(0.03 * len(appli_train))
TotalFraud = appli_train['fraud_label'].sum()
FdrTable = pd.DataFrame(columns=['Variable', 'FDR'])
appli_train_2['fraud_label'] = appli_train_2['fraud_label'].astype('float64')
for column in appli_train_2.iloc[:,2:]:
    FraudCaught = appli_train_2[[column,'fraud_label']].sort_values(by = [column], ascending = False)
    FDR = FraudCaught.iloc[0:Three_Percent,1:2].sum() / TotalFraud
    FdrTable = FdrTable.append({'Variable': column, 'FDR':float(FDR)}, ignore_index=True)


FdrTable = FdrTable.sort_values(by = 'FDR', ascending = False)
FdrTable

                            Variable       FDR
102                       FraudLabel  1.000000
27                 ssn_lastname_risk  1.000000
25                ssn_homephone_risk  1.000000
24                  ssn_nameDOB_risk  1.000000
23              ssn_fulladdress_risk  1.000000
21                      nameDOB_risk  1.000000
20                  fulladdress_risk  1.000000
28            nameDOB_homephone_risk  1.000000
29        fulladdress_homephone_risk  1.000000
30          fulladdress_nameDOB_risk  1.000000
26                ssn_firstname_risk  1.000000
19                          ssn_risk  0.996835
42                     fulladdress30  0.350462
22                    homephone_risk  0.335304
40                      fulladdress7  0.319730
39                      fulladdress3  0.296993
38                      fulladdress1  0.267594
64                      ssnnameDOB30  0.250104
94            fulladdresshomephone30  0.249854
48                       dtnameDOB30  0.249771
82                     ssnlastname30  0.246273
76                    ssnfirstname30  0.244024
93            fulladdresshomephone14  0.241276
63                      ssnnameDOB14  0.238694
75                    ssnfirstname14  0.237611
81                     ssnlastname14  0.235696
36                             ssn30  0.235279
92             fulladdresshomephone7  0.223953
74                     ssnfirstname7  0.218789
80                      ssnlastname7  0.218289
..                               ...       ...
95               fulladdressnameDOB0  0.041642
47                       dtnameDOB14  0.040060
41                     fulladdress14  0.040060
35                             ssn14  0.040060
15     diff_date.firstname_homephone  0.039810
66                     ssnhomephone1  0.039394
14       diff_date.firstname_nameDOB  0.038727
13      diff_date.firstname_lastname  0.038061
65                     ssnhomephone0  0.037062
17      diff_date.lastname_homephone  0.036729
52                          record.1  0.034980
16        diff_date.lastname_nameDOB  0.033814
10    diff_date.fulladdress_lastname  0.032814
8            diff_date.ssn_homephone  0.032731
4          diff_date.ssn_fulladdress  0.032231
9    diff_date.fulladdress_firstname  0.032231
18       diff_date.nameDOB_homephone  0.032231
11     diff_date.fulladdress_nameDOB  0.032148
101                          randNum  0.030482
12   diff_date.fulladdress_homephone  0.029066
0                      diff_date.ssn  0.024069
1              diff_date.fulladdress  0.023653
3                diff_date.homephone  0.023570
2                  diff_date.nameDOB  0.023403
6             diff_date.ssn_lastname  0.022820
7              diff_date.ssn_nameDOB  0.022737
5            diff_date.ssn_firstname  0.022737
49                        homephone0  0.010910
50                        homephone1  0.010660
51                        homephone3  0.009578

[103 rows x 2 columns]

## Calculate KS for each candidate variable

In [43]:
appli_train_3 = appli_train.copy()
KsTable = pd.DataFrame(columns=['Variable', 'KS'])
for column in appli_train_3.iloc[:,2:]:
    KS = sps.ks_2samp(appli_train_3.loc[appli_train_3['fraud_label'] == 0, column], appli_train_3.loc[appli_train_3['fraud_label'] == 1, column])
    KsTable = KsTable.append({'Variable': column, 'KS':KS[0] }, ignore_index=True)
KsTable = KsTable.sort_values(by = 'KS', ascending = False)
KsTable

                            Variable        KS
102                       FraudLabel  1.000000
30          fulladdress_nameDOB_risk  0.995313
28            nameDOB_homephone_risk  0.995145
23              ssn_fulladdress_risk  0.995131
29        fulladdress_homephone_risk  0.994044
24                  ssn_nameDOB_risk  0.993461
21                      nameDOB_risk  0.993284
25                ssn_homephone_risk  0.993034
20                  fulladdress_risk  0.992955
27                 ssn_lastname_risk  0.992474
26                ssn_firstname_risk  0.991645
19                          ssn_risk  0.986234
22                    homephone_risk  0.597312
1              diff_date.fulladdress  0.328583
42                     fulladdress30  0.327469
40                      fulladdress7  0.298084
39                      fulladdress3  0.275973
38                      fulladdress1  0.246222
5            diff_date.ssn_firstname  0.223882
6             diff_date.ssn_lastname  0.223795
2                  diff_date.nameDOB  0.223434
64                      ssnnameDOB30  0.223251
7              diff_date.ssn_nameDOB  0.223170
94            fulladdresshomephone30  0.223081
48                       dtnameDOB30  0.223080
12   diff_date.fulladdress_homephone  0.222937
82                     ssnlastname30  0.220251
76                    ssnfirstname30  0.218956
0                      diff_date.ssn  0.214436
36                             ssn30  0.214220
..                               ...       ...
11     diff_date.fulladdress_nameDOB  0.054135
18       diff_date.nameDOB_homephone  0.054075
4          diff_date.ssn_fulladdress  0.053586
99              fulladdressnameDOB14  0.045951
87                nameDOBhomephone14  0.045219
57                  ssnfulladdress14  0.045085
69                    ssnhomephone14  0.043110
98               fulladdressnameDOB7  0.028945
56                   ssnfulladdress7  0.028390
86                 nameDOBhomephone7  0.028349
52                          record.1  0.027042
68                     ssnhomephone7  0.025984
17      diff_date.lastname_homephone  0.021143
97               fulladdressnameDOB3  0.014835
55                   ssnfulladdress3  0.014674
85                 nameDOBhomephone3  0.014539
67                     ssnhomephone3  0.011983
101                          randNum  0.005897
84                 nameDOBhomephone1  0.005512
96               fulladdressnameDOB1  0.005444
54                   ssnfulladdress1  0.005341
15     diff_date.firstname_homephone  0.005035
66                     ssnhomephone1  0.002871
65                     ssnhomephone0  0.002181
95               fulladdressnameDOB0  0.001761
83                 nameDOBhomephone0  0.001753
53                   ssnfulladdress0  0.001729
41                     fulladdress14  0.000000
47                       dtnameDOB14  0.000000
35                             ssn14  0.000000

[103 rows x 2 columns]

## Compile two tables and Save to an excel

In [45]:
appli_final=KsTable.merge(FdrTable,on='Variable')

In [46]:
appli_final

                            Variable        KS       FDR
0                         FraudLabel  1.000000  1.000000
1           fulladdress_nameDOB_risk  0.995313  1.000000
2             nameDOB_homephone_risk  0.995145  1.000000
3               ssn_fulladdress_risk  0.995131  1.000000
4         fulladdress_homephone_risk  0.994044  1.000000
5                   ssn_nameDOB_risk  0.993461  1.000000
6                       nameDOB_risk  0.993284  1.000000
7                 ssn_homephone_risk  0.993034  1.000000
8                   fulladdress_risk  0.992955  1.000000
9                  ssn_lastname_risk  0.992474  1.000000
10                ssn_firstname_risk  0.991645  1.000000
11                          ssn_risk  0.986234  0.996835
12                    homephone_risk  0.597312  0.335304
13             diff_date.fulladdress  0.328583  0.023653
14                     fulladdress30  0.327469  0.350462
15                      fulladdress7  0.298084  0.319730
16                      fulladdress3  0.275973  0.296993
17                      fulladdress1  0.246222  0.267594
18           diff_date.ssn_firstname  0.223882  0.022737
19            diff_date.ssn_lastname  0.223795  0.022820
20                 diff_date.nameDOB  0.223434  0.023403
21                      ssnnameDOB30  0.223251  0.250104
22             diff_date.ssn_nameDOB  0.223170  0.022737
23            fulladdresshomephone30  0.223081  0.249854
24                       dtnameDOB30  0.223080  0.249771
25   diff_date.fulladdress_homephone  0.222937  0.029066
26                     ssnlastname30  0.220251  0.246273
27                    ssnfirstname30  0.218956  0.244024
28                     diff_date.ssn  0.214436  0.024069
29                             ssn30  0.214220  0.235279
..                               ...       ...       ...
73     diff_date.fulladdress_nameDOB  0.054135  0.032148
74       diff_date.nameDOB_homephone  0.054075  0.032231
75         diff_date.ssn_fulladdress  0.053586  0.032231
76              fulladdressnameDOB14  0.045951  0.078371
77                nameDOBhomephone14  0.045219  0.077205
78                  ssnfulladdress14  0.045085  0.077621
79                    ssnhomephone14  0.043110  0.075456
80               fulladdressnameDOB7  0.028945  0.064379
81                   ssnfulladdress7  0.028390  0.063296
82                 nameDOBhomephone7  0.028349  0.063796
83                          record.1  0.027042  0.034980
84                     ssnhomephone7  0.025984  0.059965
85      diff_date.lastname_homephone  0.021143  0.036729
86               fulladdressnameDOB3  0.014835  0.052386
87                   ssnfulladdress3  0.014674  0.052136
88                 nameDOBhomephone3  0.014539  0.052136
89                     ssnhomephone3  0.011983  0.047222
90                           randNum  0.005897  0.030482
91                 nameDOBhomephone1  0.005512  0.044391
92               fulladdressnameDOB1  0.005444  0.044307
93                   ssnfulladdress1  0.005341  0.044307
94     diff_date.firstname_homephone  0.005035  0.039810
95                     ssnhomephone1  0.002871  0.039394
96                     ssnhomephone0  0.002181  0.037062
97               fulladdressnameDOB0  0.001761  0.041642
98                 nameDOBhomephone0  0.001753  0.041642
99                   ssnfulladdress0  0.001729  0.041726
100                    fulladdress14  0.000000  0.040060
101                      dtnameDOB14  0.000000  0.040060
102                            ssn14  0.000000  0.040060

[103 rows x 3 columns]

In [48]:
with pd.ExcelWriter('HW11_new.xlsx') as writer:
    appli_final.to_excel(writer, sheet_name='KS_FDR')